name: SauceDemo
on: push

jobs:
  test_1:
    runs-on: Ubuntu-latest 

    steps:
      - name: get checkout
        uses: actions/checkout@v4
      - name: get python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - name: get googleChrome
        run: sudo apt-get install google-chrome-stable
      - name: get requirements
        run: pip install -r requirements.txt
      - name: run test
        run: pytest
